spring.datasource.url=jdbc:postgresql://localhost/meinefinanzdaten
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.profiles.active=dev


